sudo: required
services:
  - docker

before_install: 
  - docker build -t nagasaim227/docker-react -f Dockerfile.dev .


script:
  - docker run nagasaim227/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-383003276069"
  bucket_path: "docker-react"
  on:
    branch: main

  access_key_id : $$AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

##   - docker run -e CI=true nagasaim227/docker-react npm run test