sudo: required
services:
  - docker

before_install: 
  - docker build -t nagasaim227/docker-react -f Dockerfile.dev .


script:
  - docker run nagasaim227/docker-react npm run test -- --coverage




##   - docker run -e CI=true nagasaim227/docker-react npm run test